### GET/

GET http://localhost:5003 

### Register a new user

POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"om123456"
}


### Login with existing user
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"om123456"
}

### Fetch all todos GET /TODOS (protected)

GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzcyMDU3MDQ4LCJleHAiOjE3NzIxNDM0NDh9.xpzf5Fl7xEhJEobnFfKmfIQczAYg1mN078jdHUApv5A

### Create a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzcyMDU3MDQ4LCJleHAiOjE3NzIxNDM0NDh9.xpzf5Fl7xEhJEobnFfKmfIQczAYg1mN078jdHUApv5A

{
    "task":"Buy groceries"
}   
### Update a todo PUT /TODOS/:id (protected)
PUT http://localhost:5003/todos/12
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzcyMDU3MDQ4LCJleHAiOjE3NzIxNDM0NDh9.xpzf5Fl7xEhJEobnFfKmfIQczAYg1mN078jdHUApv5A

{
    "task":"Buy groceries and vegetables",
    "completed":1
}

### Delete a todo DELETE /TODOS/:id (protected)
DELETE http://localhost:5003/todos/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzcyMDU3MDQ4LCJleHAiOjE3NzIxNDM0NDh9.xpzf5Fl7xEhJEobnFfKmfIQczAYg1mN078jdHUApv5A 

